services:
  postgres_db:
    build:
      args:
        - NODE_ENV=development
  server:
    environment:
      NODE_ENV: development
      COOKIES_EXPIRATION: 0
    volumes:
      - ./server:/app
      - /app/node_modules
    command: pnpm start:dev
  web-client:
    environment:
      NODE_ENV: development
    volumes:
      - ./web-client:/app
      - /app/node_modules
    command: pnpm dev --host
    ports:
      - "5173:5173"
