services:
  postgres_db:
    build:
      context: ./server
      dockerfile: ./docker/postgres/Dockerfile
      args:
        - NODE_ENV=development
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=be_productive
    ports:
      - "5432:5432"
    network_mode: host
  server:
    build:
      context: ./server
      dockerfile: ./docker/nest/Dockerfile
      args:
        - NODE_ENV=development
    environment:
      - COOKIES_EXPIRATION=0
      - DATABASE_URL=postgres://postgres:postgres@localhost:5432/be_productive
      - SECRET=secret
    volumes:
      - ./server:/app
      - /app/node_modules
    command: pnpm start:dev
    depends_on:
      - postgres_db
    ports:
      - "3000:3000"
    network_mode: host
  web-client:
    build:
      args:
        - NODE_ENV=development
        - VITE_BACKEND_URL=http://localhost:3000
      context: ./web-client
      dockerfile: ./Dockerfile
    volumes:
      - ./web-client:/app
      - /app/node_modules
    command: pnpm dev --host --port 4173
    ports:
      - "4173:4173"
    network_mode: host