services:
  server:
    build:
      context: ./server
      dockerfile:  ./docker/nest/Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - "3000:3000"
    network_mode: "host"
  web-client:
    build:
      context: ./web-client
      dockerfile:  ./Dockerfile
      args:
        - NODE_ENV=production
    depends_on:
        - server
    ports:
        - "4173:4173"
    network_mode: "host"
