services:
  server:
    build:
      context: ./server
      dockerfile:  ./docker/nest/Dockerfile
      args:
        - NODE_ENV=production
    environment:
      - COOKIES_EXPIRATION=${COOKIE_EXPIRATION}
      - DATABASE_URL=${DATABASE_URL}
      - SECRET=${SECRET}
    ports:
      - "3000:3000"
    #networks:
    #  - network
    network_mode: host
  web-client:
    build:
      context: ./web-client
      dockerfile:  ./Dockerfile
      args:
        - NODE_ENV=production
    environment:
      - VITE_BACKEND_URL="${HOST_URL:-localhost}/api"
    depends_on:
        - server
    ports:
        - "4173:4173"
    #networks:
    #  - network
    network_mode: host
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=${HOST_URL:-localhost}
      - NGINX_PORT=80
    #networks:
    #  - network
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web-client
      - server


networks:
  network:
    driver: bridge